#!/usr/bin/env python3
"""
One-off migration: move Telegram credentials from agents onto channels.

Agents originally held their own bot token. Channels now do, because the
credential belongs to the transport rather than to the mind behind it, and
because you should be able to change how people reach an agent without
rebuilding the agent.

This reads each agent's generated environment file, and for any agent that has a
token but no channel, creates the channel and rebinds it. The token is moved
between files and never printed, echoed, or passed on a command line.

Idempotent: an agent that already has a channel is skipped, so re-running is
safe.

    sudo python3 /opt/moni-ai-os/deploy/migrate-to-channels.py [--dry-run]
"""

import json
import os
import re
import subprocess
import sys
import tempfile
from datetime import datetime, timezone

AGENTS_DIR = "/opt/moni-agents/agents"
CHANNELS_DIR = "/opt/moni-agents/channels"
AGENT_USER = "moniagent"
SLUG_RE = re.compile(r"^[a-z][a-z0-9-]{1,30}$")

DRY = "--dry-run" in sys.argv


def read_env(path):
    values = {}
    try:
        with open(path, encoding="utf-8", errors="replace") as fh:
            for line in fh:
                line = line.strip()
                if not line or line.startswith("#"):
                    continue
                key, _, value = line.partition("=")
                values[key.strip()] = value.strip()
    except OSError:
        pass
    return values


def channel_exists_for(agent):
    if not os.path.isdir(CHANNELS_DIR):
        return None
    for slug in os.listdir(CHANNELS_DIR):
        meta_path = os.path.join(CHANNELS_DIR, slug, "channel.json")
        try:
            with open(meta_path) as fh:
                if json.load(fh).get("agent") == agent:
                    return slug
        except Exception:
            continue
    return None


def free_slug(base):
    slug = base
    n = 2
    while os.path.exists(os.path.join(CHANNELS_DIR, slug)):
        slug = base + "-" + str(n)
        n += 1
    return slug


def main():
    import grp
    import pwd

    if os.geteuid() != 0:
        sys.exit("run this with sudo")
    if not os.path.isdir(AGENTS_DIR):
        print("no agents directory; nothing to migrate")
        return

    uid = pwd.getpwnam(AGENT_USER).pw_uid
    gid = grp.getgrnam(AGENT_USER).gr_gid
    os.makedirs(CHANNELS_DIR, exist_ok=True)
    os.chown(CHANNELS_DIR, uid, gid)
    os.chmod(CHANNELS_DIR, 0o750)

    migrated = []
    for agent in sorted(os.listdir(AGENTS_DIR)):
        if not SLUG_RE.match(agent):
            continue
        agent_path = os.path.join(AGENTS_DIR, agent)
        if not os.path.isdir(agent_path):
            continue

        existing = channel_exists_for(agent)
        if existing:
            print("  %-20s already connected to channel '%s'" % (agent, existing))
            continue

        env = read_env(os.path.join(agent_path, "agent.env"))
        token = env.get("TELEGRAM_BOT_TOKEN", "")
        if not token:
            print("  %-20s no token to migrate" % agent)
            continue

        slug = free_slug(agent + "-telegram")
        username = env.get("TELEGRAM_BOT_USERNAME", "")
        meta = {
            "slug": slug,
            "name": ("@" + username) if username else (agent + " Telegram"),
            "type": "telegram",
            "agent": agent,
            "telegram_bot_username": username,
            "allowed_users": env.get("ALLOWED_USERS", ""),
            "topics_enabled": env.get("ENABLE_PROJECT_THREADS", "false") == "true",
            "topics_chat_id": env.get("PROJECT_THREADS_CHAT_ID", ""),
            "addons": ["voice_notes", "file_capture", "image_capture", "quick_actions"],
            "addon_env": {},
            "migrated_from_agent": agent,
            "updated_at": datetime.now(timezone.utc).isoformat(),
        }

        print(
            "  %-20s -> channel '%s' (@%s, token %d chars)"
            % (agent, slug, username or "?", len(token))
        )
        if DRY:
            continue

        path = os.path.join(CHANNELS_DIR, slug)
        os.makedirs(path, exist_ok=True)

        fd, tmp = tempfile.mkstemp(dir=path)
        with os.fdopen(fd, "w") as fh:
            fh.write("# Generated by the MONI dashboard.\n")
            fh.write("CHANNEL_TOKEN=" + token + "\n")
        os.chown(tmp, uid, gid)
        os.chmod(tmp, 0o600)
        os.replace(tmp, os.path.join(path, "channel.env"))

        meta_path = os.path.join(path, "channel.json")
        with open(meta_path, "w") as fh:
            json.dump(meta, fh, indent=2, sort_keys=True)
            fh.write("\n")
        os.chown(meta_path, uid, gid)
        os.chmod(meta_path, 0o640)
        os.chown(path, uid, gid)
        os.chmod(path, 0o770)

        # Strip the Telegram fields the agent no longer owns, so the next update
        # from the panel does not resurrect stale values.
        agent_json = os.path.join(agent_path, "agent.json")
        try:
            with open(agent_json) as fh:
                cfg = json.load(fh)
            for key in (
                "telegram_bot_username",
                "allowed_users",
                "enable_project_threads",
                "project_threads_chat_id",
            ):
                cfg.pop(key, None)
            cfg.setdefault("addons", ["memory", "git"])
            cfg.setdefault("addon_env", {})
            with open(agent_json, "w") as fh:
                json.dump(cfg, fh, indent=2, sort_keys=True)
                fh.write("\n")
            os.chown(agent_json, uid, gid)
            os.chmod(agent_json, 0o640)
        except Exception as exc:
            print("    ! could not tidy agent.json: %s" % exc)

        migrated.append((agent, slug))

    if not migrated:
        print("\nNothing migrated.")
        return

    print("\nRegenerating agent environments from their new channels...")
    for agent, _slug in migrated:
        r = subprocess.run(
            ["/usr/local/sbin/moni-helper", "agent-update"],
            input=json.dumps({"slug": agent}),
            capture_output=True,
            text=True,
            timeout=120,
        )
        state = "ok" if r.returncode == 0 else "FAILED: " + r.stdout.strip()[:200]
        print("  %-20s %s" % (agent, state))

    print("\nDone. %d agent(s) migrated." % len(migrated))


if __name__ == "__main__":
    main()
